services:
  - type: web
    name: bms
    runtime: php
    buildCommand: |
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo add-apt-repository ppa:ondrej/php
      sudo apt-get update
      sudo apt-get install -y php8.2
      php -v
      composer install --no-dev --optimize-autoloader
      php artisan migrate --force
      php artisan db:seed --force
      npm install
      npm run prod
    ...
